# Generated by Django 3.0.4 on 2020-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptname', models.CharField(max_length=25)),
                ('ptemail', models.CharField(max_length=25)),
                ('diseasename', models.CharField(max_length=25)),
                ('deaseasedesciptioncategory', models.CharField(max_length=40)),
                ('medicinename', models.CharField(max_length=25)),
                ('directiontopatient', models.TextField()),
                ('filefield', models.ImageField(default='doctors/images/doctor.png', upload_to='images/')),
            ],
        ),
    ]
