# Generated by Django 3.0.4 on 2020-04-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='filefield',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
