# Generated by Django 3.0.4 on 2020-04-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20200403_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='filefield',
            field=models.ImageField(upload_to='prescription/'),
        ),
    ]
