# Generated by Django 3.0.4 on 2020-03-30 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='img',
            field=models.ImageField(default='doctors/images/doctor.png', upload_to='images/'),
        ),
    ]
